cli: fix error parsing input arguments in non-interactive mode
Causes the following failure:

   $ /bin/nmcli connection add type ethernet con-name connie ifname '*'

   (process:13883): GLib-CRITICAL **: g_strchug: assertion `string != NULL' failed
   (process:13883): GLib-CRITICAL **: g_strchomp: assertion `string != NULL' failed
   Error: invalid connection type; '' not among [generic, ...].

Regression introduced by commit bfb1200b4f279f83c113d048839044ad51ca2af7.

Signed-off-by: Thomas Haller <thaller@redhat.com>