build/dns: fix compilation error due to invalid #include path
Out-of-tree build fails with:
  ../../src/dns-manager/nm-dns-manager.c:38:33: fatal error: libnm-util/nm-utils.h: No such file or directory

Fixes regression introduced by commit 7580cfef20386da22f9c3d8bd20b2ab8fd954a05.

Signed-off-by: Thomas Haller <thaller@redhat.com>