core: fix wrong g_return_if_fail() statement when value should be returned in NMManager:assume_connection()
    CC       nm-manager.lo
  nm-manager.c: In function 'assume_connection':
  nm-manager.c:1605:345: error: 'return' with no value, in function returning non-void [-Werror=return-type]
    g_return_if_fail (nm_device_get_state (device) >= NM_DEVICE_STATE_DISCONNECTED);

Minor error, introduced by commit f229f4e201c9b6aefddafcee362b99d2ef6ab40c.

Signed-off-by: Thomas Haller <thaller@redhat.com>